---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{ with .Values.labels }}{{ tpl ( toYaml . ) $ | indent 4 }}{{ end }}
  {{- with .Values.annotations }}
  annotations: {{ tpl ( toYaml . ) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      helm.sh/from: deploy.{{ include "app.fullname" . }}
  {{- with .Values.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        helm.sh/chart: {{ include "app.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/from: deploy.{{ include "app.fullname" . }}
{{ with .Values.podLabels }}{{ tpl ( toYaml . ) $ | indent 8 }}{{ end }}
      {{- with .Values.podAnnotations }}
      annotations: {{ tpl ( toYaml . ) $ | nindent 8 -}}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl ( toYaml . ) $ | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.args }}
          args: {{ tpl ( toYaml . ) $  | nindent 12 }}
          {{- end }}
          {{- with .Values.envVariables }}
          env: {{ tpl ( toYaml . ) $ | nindent 12 }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: 7000
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe: {{ tpl ( toYaml . ) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{ tpl ( toYaml . ) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{ tpl ( toYaml . ) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext: {{ tpl ( toYaml . ) $ | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ tpl ( toYaml . ) $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.fullname" . }}
      {{- with .Values.affinity }}
      affinity: {{ tpl ( toYaml . ) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ tpl ( toYaml . ) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext: {{ tpl ( toYaml . ) $ | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end}}
